### ISSUE TITLE
Underscores producing weird error

### ISSUE THREAD

**Issue by coderkoala** [orionmelt/snoopsnoo#13]
![image](https://user-images.githubusercontent.com/30156167/60285629-c63d6080-992d-11e9-8eff-43acc5d42b49.png)
There seems to be a weird issue where the app just throws an unexpected error if the username consists of an underscore. Is this intended behavior? I tried a few other handles, every one of them produced the same error.

**Comment by SockHungryClutz** [comment]
This isn't due to underscores, this is an issue with orienmelt's app key for blockspring being expired. What you're seeing here occurs because:
* you request to see a user, snoopsnoo tries to find the user in its database
* the user isn't found, so your browser then makes a request to the snoopsnoo/get API
* this in turn makes a request to blockspring with the expired app key since it's hardcoded into the snoopsnoo website
* blockspring rejects this request since the app key is expired
* an error is shown

see my issue #12 , it is unlikely that this will be solved since orionmelt hasn't been active on reddit, or apparently even remotely looking at this service, in months.

**Comment by coderkoala** [comment]
@SockHungryClutz that was insightful, thanks. I'll try to see what I can do about it this weekend, see if I can make a fork and try to host it on my own :V

Perhaps the vague error threw me off haha.
